name: "acquisition_cdc_lakehouse"
version: "1.0.0"
config-version: 2

profile: "acquisition_cdc_lakehouse"

model-paths: ["models"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
macro-paths: ["macros"]
test-paths: ["tests"]

models:
  acquisition_cdc_lakehouse:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
